Pub 2184 green colour indicator to signify when password criteria is met
hmcts/pip-shared-infrastructures pull request #167
Opened 2024-04-12 13:25 UTC by MindGames2015

**Before creating a pull request make sure that:**

- [X] commit messages are meaningful and follow good commit message guidelines
- [X] README and other documentation has been updated / added (if needed)
- [X] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

https://tools.hmcts.net/jira/browse/PUB-2345

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-04-12 13:49 UTC, ChrisS1512 requested changes

2024-04-12 13:49 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +        href="https://pipsssastg.blob.core.windows.net/b2c-custom-policy-files/favicon.ico"
These need to be changed back to the dynamic values previously, as they're replaced by infrastructure (there's a few below which are similar)

2024-04-12 13:49 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-en.html
This looks like a copy of the HTML file when rendered by Azure.

This need to be changed back to the current file and only contain the changes needed for this new functionality.

2024-04-12 13:49 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +      <div id="api" data-name="SelfAsserted" class="govuk-grid-column-two-thirds">
I do not believe this should be changed. the div for id="api" is injected into by Azure. The below code in this dev element I believe is from that injection, and therefore can be removed. I think it's only the div on line 139 that is the new block here?

2024-04-15 12:02 UTC, MindGames2015 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +        href="https://pipsssastg.blob.core.windows.net/b2c-custom-policy-files/favicon.ico"
Changes made. Thanks Chris

2024-04-15 12:03 UTC, MindGames2015 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +      <div id="api" data-name="SelfAsserted" class="govuk-grid-column-two-thirds">
Changes made. Thanks Chris.

2024-04-15 12:45 UTC, ChrisS1512 requested changes

2024-04-15 12:45 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +        <img src="{StorageAccountUrl}{B2cContainer}/logo_gov.png" height="17" width="41"
Not sure if this should have been changed - should this still be copyright?

2024-04-15 12:45 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-cy-GB.html
> +      <div id="api" data-name="SelfAsserted" class="govuk-grid-column-two-thirds">
Un-resolving as issue still exists. I believe Everything within the div tag starting on line 71 until it's close on line 128 is auto injected by Azure so they do not need adding here, and only the div tag itself should exist. Were there any changes in this div block specific to the new functionality?

2024-04-15 12:45 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw-en.html
> +      <div id="api" data-name="SelfAsserted" class="govuk-grid-column-two-thirds">
Same comment here as above regarding div tag

2024-04-15 12:45 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/reset-pw.css
> +  background-image: url("https://pipsssastg.blob.core.windows.net/b2c-custom-policy-files/govuk-crest.png");
This also needs changing back to the parameterised version. Same on line 3955

2024-04-15 13:19 UTC, closed without merging