PUB-1931 Move forgot password link
hmcts/pip-shared-infrastructures pull request #90
Opened 2023-03-30 11:18 UTC by KianKwa

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/PUB-1931

### Change description ###

Move forgot password link

![image](https://user-images.githubusercontent.com/80688761/228819974-599928eb-7451-43ef-8fcd-ff736751b138.png)

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-03-30 11:51 UTC, ChrisS1512 requested changes

2023-03-30 11:51 UTC, ChrisS1512 commented on infrastructure/resources/b2c-polices/login.css
> +  font-family: "GDS Transport", arial, sans-serif;
Looks like a duplicate font family. One can removed

2023-03-30 14:02 UTC, ChrisS1512 approved these changes

2023-03-31 15:31 UTC, junaidiqbalmoj approved these changes

2023-04-05 11:51 UTC, merged